### ISSUE TITLE
influxdb exporter - group by endpoint

### ISSUE THREAD

**Issue by zgolus** [devopsfaith/krakend-opencensus#11]
Hi!

I'm trying to monitor a krakend gateway using krakend-opencensus with influxdb as an exporter. I can see metrics being written to the database declared in exporters section of the config file, but the data sent to influx can't be filtered or grouped by endpoint as they are missing a name field / tag:

```
SELECT * FROM "opencensus.io/http/server/request_count" limit 10
name: opencensus.io/http/server/request_count
time                count
----                -----
1535013524000000000 7
1535013525000000000 14
1535013526000000000 21
1535013527000000000 27
1535013528000000000 34
1535013529000000000 40
1535013530000000000 47
1535013531000000000 54
1535013532000000000 61
1535013533000000000 68
```
And this it my krakend config file:

```
{
    "version": 2,
    "extra_config": {
        "github_com/devopsfaith/krakend-metrics": {
            "collection_time": "60s",
            "proxy_disabled": false,
            "router_disabled": false,
            "backend_disabled": false,
            "endpoint_disabled": false,
            "listen_address": ":8090"
        },
        "github_com/devopsfaith/krakend-gologging": {
            "level": "WARNING",
            "prefix": "[KRAKEND]",
            "syslog": false,
            "stdout": true
        },
        "github_com/devopsfaith/krakend-opencensus": {
            "sample_rate": 100,
            "reporting_period": 1,
            "enabled_layers": {
                "backend": true,
                "router": true,
                "pipe": true
            },
            "exporters": {
                "influxdb": {
                    "address": "http://influxdb:8086",
                    "db": "opencensus",
                    "timeout": "1s"
                },
                "logger": {}
            }
        }
    },
    "output_encoding": "json",
    "timeout": "3000ms",
    "cache_ttl": "300s",
    "name": "MyKraken",
    "endpoints": [
        {
            "endpoint": "/test",
            "method": "GET",
            "output_encoding": "json",
            "concurrent_calls": 1,
            "querystring_params": [],
            "backend": [
                {
                    "url_pattern": "/test",
                    "encoding": "json",
                    "extra_config": {},
                    "sd": "static",
                    "host": [
                        "http://test:8000"
                    ],
                    "disable_host_sanitize": false
                }
            ]
        }
    ],
    "disable_rest": true
}
```
So is the lack of endpoint tag intentional or perhaps I'm missing something in my configuration?

Thanks in advance!

**Comment by alombarte** [comment]
Hi @zgolus,

You are right. The opencensus implementation is in its early stages and we are just offering a limited set of features. Please have a look at the following relevant links if you would like to explore a little bit further:

- https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/stats.go#L73
- https://github.com/devopsfaith/krakend-opencensus/blob/master/opencensus.go#L81
- https://github.com/devopsfaith/krakend-opencensus/blob/master/opencensus.go#L136

In the meantime we will evaluate what would be the impact of adding the [details](https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/server.go#L127) in the context.

Hope this helps,
Thanks

**Comment by zgolus** [comment]
Hi @alombarte,

Thank you for the clarification. I will try to follow your links, but I'm no Go developer (no pun intended). For now I switched to letgoapp/krakend-influx, which delivers metrics tagged with endpoint.

Best,
Jakub
