### ISSUE TITLE
Prometheus exporter doesn't show endpoints

### ISSUE THREAD

**Issue by victor-bortone** [devopsfaith/krakend-opencensus#23]
Hi, do you have plans on improving the Prometheus exporter?

In particular, I would like to monitor all Krakend endpoints through the Prometheus exporter, but currently it doesn't show anything about the different endpoints configured, only a very broad view of the entire gateway. For example, I would like to know how many times each endpoint was called, the average latency, counts by HTTP status etc. I've noticed that the /__stats/ endpoint has all the information I need, but in a different format, not easily accessible by the tools we use (Prometheus and Grafana).

**Comment by reneherrero** [comment]
Looking for the same here

**Comment by PhilippHeuer** [comment]
Looking for this feature too, playing around at https://github.com/PhilippHeuer/krakend-opencensus/tree/feature/prometheus-details to try to get this to work - if i do i will create a pr for this.

**Comment by breml** [comment]
@PhilippHeuer I looked at your branch and this looks interesting to me as well. What is the current state?

**Comment by PhilippHeuer** [comment]
I created a pr and got feedback, you can follow progress there: https://github.com/devopsfaith/krakend-opencensus/pull/27

The current state still has a issue with metric cardinality im trying to fix, but i didn't figure this out yet :(
