### ISSUE TITLE
More control over metrics cardinality and the `tag_path` option

### ISSUE THREAD

**Issue by mzanibelli** [devopsfaith/krakend-opencensus#51]
Hi,

We've been experiencing problems when enabling the `PathTag` option for Prometheus.

### Reproduction

Enable the `tag_path` option in KrakenD and declare an endpoint with a variable parameter.
For example `/foo/{id}`.
Then, perform multiple requests with `curl krakend.localhost/foo/$RANDOM`: the server's memory will be growing fast.

### Cause

Since client metrics perform parameter interpolation, a high number of different Prometheus labels are created. This has bad consequence:
- for server memory usage which is leaking
- for TSDB cardinality which rapidly gets a high number of new time series

### How to avoid this

Parameter interpolation seems only performed in client metrics. In server metrics however, a single lablel `/foo/{id}` will be created.
Thus, it would be useful to be able to enable `tag_path` only for server metrics or disable parameter interpolation for client metrics.

**Comment by alombarte** [comment]
Hi @mzanibelli, please have a look at https://github.com/devopsfaith/krakend-opencensus/pull/27 and the patience of @PhilippHeuer for over a year with us for context of this functionality.

The `tag_path` can be disabled. But from here I am opening the discussion for anyone willing to participate.

**Comment by mzanibelli** [comment]
Hey @alombarte, thanks for pointing me out this thread.
I just missed the new `HTTPRequestExecutorFromConfig` and still used the old version without passing the configuration in my backend factory. This resulted in my `http_client*` metrics not being correctly aggregated by path.

I fixed my factory and now everything is correctly aggregated.

Thank you a lot for your help 😄
