### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by andrei1489** [devopsfaith/krakend-opencensus#6]
Hi!

Created a docker container with krakend and wanted to monitor it with influxdb and grafana. Configured InfluxDB as another container, and in the opencensus plugin, configured Graphana to use it as a datasource and then added the provided dashboard(https://grafana.com/dashboards/5722). I noticed in the network connections tab that the query to InfluxDB ( "show tag values with key = host" ) returned an empty statement. I inspected the db manually and only found the following tags:
```
> show tag keys
name: opencensus.io/http/client/latency_buckets
tagKey
------
bucket

name: opencensus.io/http/client/request_bytes_buckets
tagKey
------
bucket

name: opencensus.io/http/client/request_count_by_method
tagKey
------
http.method

name: opencensus.io/http/client/response_bytes_buckets
tagKey
------
bucket

name: opencensus.io/http/client/response_count_by_status_code
tagKey
------
http.status

name: opencensus.io/http/server/latency_buckets
tagKey
------
bucket

name: opencensus.io/http/server/request_bytes_buckets
tagKey
------
bucket

name: opencensus.io/http/server/request_count_by_method
tagKey
------
http.method

name: opencensus.io/http/server/response_bytes_buckets
tagKey
------
bucket

name: opencensus.io/http/server/response_count_by_status_code
tagKey
------
http.status
```
Is the dashboard supposed to be used with a custom config?

Thanks!

**Comment by alombarte** [comment]
Hi @andrei1489, I am not 100% sure now, but I think this dashboard is to be used specifically with the` krakend-influxdb` middleware...

**Comment by andrei1489** [comment]
hi @alombarte  and thanks for the speedy reply.

Is the krakend-influxdb middleware still current? I found references to it in the other report, but github returns a 404 when trying to access the project. 

If it has been discontinued , this issue can be closed. If not, can you provide a link to it? I checked http://www.krakend.io/blog/krakend-0.5-release-notes/ and opencensus seemed to be the only one with influxdb

Thanks again.

**Comment by alombarte** [comment]
Oh! You are right, link in the contrib repository is broken. I will fix it now

The Influx middleware is a contribution from the company Letgo.com and is in their space:
https://github.com/letgoapp/krakend-influx

**Comment by andrei1489** [comment]
Thanks a lot @alombarte . 
I managed to get krakend-influx working with grafana after a bit of reverse engineering. 

Thanks again and keep up the good work.

**Comment by andrei1489** [comment]
@alombarte I made a pull request on their repo to add an examples page. Also the grafana dashboard json had some hardcoded influxdb datasources, which I fixed and included in the examples page.
